config/routes.rb
Rails.application.routes.draw do

  # get 'menus/section_id:integer'
  # get 'menus/item_id:integer'

  get "/" => "homes#index"
  get "/contact-us" => "homes#contact_us"
  resources :homes
  resources :menus
  resources :items
  resources :orders

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :sections
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    # redirect_to '/homes/home.html.erb'
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def show
    @item = Item.find_by_id(params[:id])
  end

  def create
  end

  def destroy
  end

  def index
    @items = Item.all()
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
    if params[:section]
      section = Section.find_by_name(params[:section])
      @items = Item.where(section_id: section.id).all
    else
      section = Section.all()
      @items = Item.all()
    end

    if params[:search]
      @items = Item.where("name LIKE ? ",params[:search])
    end

    @sections = Section.all()

    # if params[:sort_by]
  end

  def create
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all()
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: 'Thank you for your order.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @order = Order.new
  end

  def show
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_name, :customer_phone, :customer_address, :quantity, :item_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/homes/contact_us.html.erb
<link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lora" rel="stylesheet">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<body style="background-color: #09C4BB">

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #e3f2fd;">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">
      <img src="http://www.thedesignlove.com/wp-content/uploads/2017/01/037-Seafood-Chef-Logo-Template.jpg" width="30" height="30" alt="">
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active">
        <%= link_to 'Home', "/", class:"nav-link" %>
        </li>

        <li class="nav-item active">
        <%= link_to 'Menu', "/menus?section=Breakfast", class:"nav-link" %>
        </li>

        <li class="nav-item active">
        <%= link_to 'Contact Us'.html_safe, "/contact-us", class:"nav-link" %>
        </li>

      </ul>
    </div>
  </nav>

  <div style="color:white">
      <p class="text-center" style="font-family: 'Lora', cursive; font-size: 70px; color:white;" ><b> Contact Us </b></p>
      <div class="row">
        <div class="col"></div>
        <div class="col"><i class="glyphicon glyphicon-home" ></i> Xuan Dieu, Quy Nhon city, Binh Dinh province, VietNam </div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col"> <i class="glyphicon glyphicon-envelope" ></i> contact@lyti.com </div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col"><i class="glyphicon glyphicon-earphone" ></i> 0986995459 </div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col"><i class="glyphicon glyphicon-thumbs-up" ></i> https://facebook.com/lyti </div>
        <div class="col"></div>
      </div>
      <div class="row">
        <div class="col"></div>
        <div class="col"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3922.400288580428!2d109.24179841932613!3d13.772306631701738!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x9a3f40efc7259557!2sSurf+Bar!5e0!3m2!1sen!2s!4v1487436616474" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe> </div>
        <div class="col"></div>
      </div>
  </div>
</body>

app/views/homes/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Shrikhand" rel="stylesheet">

<body background="http://i.imgur.com/eW1xgkG.png" style="width: 100vw; height: 100vh; background-repeat: no-repeat; background-position: center center;">
  <div class="row">
    <div class="col"> </div>
    <div class="col-8"></div>
    <div class="col">
      <%= link_to "Menu", menus_path(section: "Breakfast"), class:"btn btn-outline-success" %>
      <%= link_to "Contact Us", contact_us_path, class:"btn btn-outline-success" %>
    </div>
  </div>
<div class="container-fluid" style="height: 100%; display: flex; justify-content: center; align-items: center;">
  <div>
    <p class="text-center" style="font-family: 'Shrikhand', cursive; font-size: 70px;" ><b> LyTi's </b></p>
    <p class="text-center" style="font-family: 'Shrikhand', cursive; font-size: 70px;" ><b> By The Beach </b></p>
  </div>
</div>

</body>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #e3f2fd;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <a class="navbar-brand" href="/">
      <img src="http://www.thedesignlove.com/wp-content/uploads/2017/01/037-Seafood-Chef-Logo-Template.jpg" width="30" height="30" alt="">
    </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
      <%= link_to 'Home', "/", class:"nav-link" %>
      </li>

      <li class="nav-item active">
      <%= link_to 'Menu', menus_path, class:"nav-link" %>
      </li>

      <li class="nav-item active">
      <%= link_to 'Contact Us', "/contact-us", class:"nav-link" %>
      </li>

    </ul>

  </div>
</nav>

<div class="container">
  <h1 class="text-center"> <%= @item.name%> </h1>
  <p class="text-center"> <%= @item.description%> </p>

    <img src="<%= @item.image_url %>" alt="Card image cap" style="width:80%; height:80%;" >
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.css">

<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.js"></script>
<script>
$(document).ready( function () {
    $('#myTable').DataTable();
} );
</script>


<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #e3f2fd;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <a class="navbar-brand" href="/">
      <img src="http://www.thedesignlove.com/wp-content/uploads/2017/01/037-Seafood-Chef-Logo-Template.jpg" width="30" height="30" alt="">
    </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
      <%= link_to 'Home', homes_path, class:"nav-link" %>
      </li>

      <li class="nav-item active">
      <%= link_to 'Contact Us', "/contact-us", class:"nav-link" %>
      </li>

    </ul>

  </div>
</nav>

<div class="container-fluid" style="width: 80%;">

  <h1 class="text-center"> MENU </h1>

  <ul style="text-align:center;" class="nav nav-tabs">

    <% @sections.each do |section| %>
      <div class="nav-item nav-link <%= 'active' if params[:section] == section.name %>" >
        <%= link_to section.name, controller: menus_path,section: section.name %>
      </div>
    <% end %>

  </ul>

  <table id="myTable" class="display table" style="margin-top:10px;">
    <thead>
      <tr>
        <th>#</th>
        <th style="width:20%">Name</th>
        <th>Description</th>
        <th style="width:10%">Price</th>
        <th>Image</th>
        <th>Order</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each_with_index do |item, index| %>
      <tr>
        <th><%= index + 1 %></th>
          <td style="width:20%"><%= link_to item.name, item_path(item) %></td>
          <td><%= item.description %></td>
          <td style="width:10%"><%= item.price %> </td>
          <td><img src="<%= item.image_url %>" style="with:100px; height: 100px;"></img></td>
          <td> <%= link_to 'order', new_order_path(item_id: item.id) %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-1">

      <div class="field">
        <%= f.label "Name:" %>
        <%= f.text_field :customer_name %>
      </div>

      <div class="field">
        <%= f.label "Phone:" %>
        <%= f.text_field :customer_phone %>
      </div>

      <div class="field">
        <%= f.label "Address:" %>
        <%= f.text_field :customer_address %>
      </div>

      <div class="field">
        <%= f.label "Quantity:" %>
        <%= f.text_field :quantity %>
      </div>

      <div class="field">
        <%= f.hidden_field :item_id, :value => params[:item_id] %>
      </div>

      <div class="action">
        <%= f.submit "Submit", :item_id => params[:item_id], class:"btn btn-warning" %>
      </div>

    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="container">
<h1>Editing Order</h1>

<div class="row">
  <div class="col-sm-8">
    <%= render 'form', order: @order %>
  </div>
</div>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>
</div>

app/views/orders/index.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="background-color: #e3f2fd;">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <a class="navbar-brand" href="/">
      <img src="http://www.thedesignlove.com/wp-content/uploads/2017/01/037-Seafood-Chef-Logo-Template.jpg" width="30" height="30" alt="">
    </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active">
      <%= link_to 'Home', homes_path, class:"nav-link" %>
      </li>

      <li class="nav-item active">
      <%= link_to 'Menu', menus_path, class:"nav-link" %>
      </li>

      <li class="nav-item active">
      <%= link_to 'Contact Us', "/contact-us", class:"nav-link" %>
      </li>

    </ul>

  </div>
</nav>

<div class="container">
  <h1> Order List </h1>

  <table class="table" style="margin-top:10px;">
    <thead>
      <tr>
        <th>#</th>
        <th style="width:20%">Name</th>
        <th> Food </th>
        <th> Quantity </th>
        <th>Address</th>
        <th style="width:10%">Phone</th>
        <th>Created</th>
        <th>Total Cost</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each_with_index do |order, index| %>
      <tr>
        <th><%= index + 1 %></th>
          <td style="width:20%"><%= order.customer_name %></td>
          <td> <%= order.item.name %> </td>
          <td> <%= order.quantity %>
          <td><%= order.customer_address %></td>
          <td style="width:10%"><%= order.customer_phone %> </td>
          <td> <%= "#{order.created_at.strftime("%A")}, #{order.created_at.strftime("%B")}, #{order.created_at.strftime("%Y")}, #{order.created_at.strftime("%H")}:#{order.created_at.strftime("%I")} #{order.created_at.strftime("%p")}" %> </td>
          <td> <%= order.item.price * order.quantity + 20000 %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/orders/new.html.erb
<div class="container">
<h1>New Order</h1>

<div class="row">
  <div class="col-sm-8">
      <%= render 'form', order: @order %>
  </div>
</div>
<%= link_to 'Back', menus_path %>
</div>

app/views/orders/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.customer_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.customer_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @order.customer_phone %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
</div>